apiVersion: v1
kind: ConfigMap
metadata:
  name: cortexops-common-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cortexops.labels" . | nindent 4 }}
data:
  CORTEXOPS_ENV: {{ .Values.global.environment | quote }}
  LOG_LEVEL: {{ .Values.global.logLevel | quote }}
  POSTGRES_HOST: "infra-pgdb"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  NATS_URL: "nats://infra-nats:4222"
  REDIS_HOST: "infra-redis"
  REDIS_PORT: "6379"
  IDENTITY_DATABASE_URL: "postgresql://postgres:password@infra-pgdb:5432/identity"
  KEYCLOAK_URL: "http://infra_keycloak:8080"
  KEYCLOAK_REALM: "cortexops"
  KEYCLOAK_CLIENT_ID: "cortexops-backend"
  KEYCLOAK_CLIENT_SECRET: "Ulm6g7u1kcFWDb9kyT5qtfZmM6kAWDca"
  KEYCLOAK_ADMIN_USER: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "adminpassword"