apiVersion: v1
kind: Secret
metadata:
  name: cortexops-common-secrets
  namespace: cortexops-system
type: Opaque
stringData:
  NATS_URL: "nats://infra-nats:4222"
  NATS_PORT: "4222"
  REDIS_HOST: "infra-redis"
  REDIS_PORT: "6379"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "postgres"
  IDENTITY_DATABASE_URL: "postgresql://postgres:password@infra-pgdb:5432/identity"
  KEYCLOAK_URL: "http://infra-keycloak:8080"
  KEYCLOAK_REALM: "cortexops"
  KEYCLOAK_CLIENT_ID: "cortexops-backend"
  KEYCLOAK_CLIENT_SECRET: "Ulm6g7u1kcFWDb9kyT5qtfZmM6kAWDca"
  KEYCLOAK_ADMIN_USER: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "adminpassword"
  ORGANIZATION_DATABASE_URL: "postgresql://postgres:password@infra-pgdb:5432/organization"
  WORKFLOW_DATABASE_URL: "postgresql://postgres:password@infra-pgdb:5432/workflow"
  AGENT_RUNTIME_DATABASE_URL: "postgresql://postgres:password@infra-pgdb:5432/agent_runtime"

